workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    environment:
      android_signing:
        - Calc_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "io.codemagic.Calculator-Apps"
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - f20250443@hyderabad.bits-pilani.ac.in
        notify:
          success: true
          failure: false
