workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    environment:
      android_signing:
        - Calc_keystore   # <-- this stays here
      vars:
        PACKAGE_NAME: "com.calculator.app"
    scripts:
      # 1. Install npm dependencies
      - name: Install npm packages
        script: |
          npm install

      # 2. Build web assets (JS/CSS/HTML for Capacitor)
      - name: Build web assets
        script: |
          npm run build

      # 3. Copy web assets into Android project
      - name: Copy web assets to Android
        script: |
          npx cap copy android

      # 4. Clean & build Android release APK
      - name: Build release APK
        script: |
          cd android
          ./gradlew clean assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - f20250443@hyderabad.bits-pilani.ac.in
        notify:
          success: true
          failure: false
