workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.calculator.app"
      android_signing:
        - Calc_keystore
    scripts:
      - name: Install npm packages
        script: |
          npm install

      - name: Build web assets
        script: |
          npm run build

      - name: Copy web assets to Android
        script: |
          npx cap copy android

      - name: Build release APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - f20250443@hyderabad.bits-pilani.ac.in
        notify:
          success: true
          failure: false
